name: application
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=3.0.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  flutter_switch: ^0.3.2
  pin_code_fields: ^8.0.1
  carousel_slider: ^7.0.0
  smooth_page_indicator: ^1.2.0+3
  responsive_grid_list: ^1.4.0
  readmore: ^3.0.0
  connectivity_plus: ^6.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsLight.ttf
          weight: 300